// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4_yaggdYnJV_nqEzy4cIIBmejI1SbUIM',
    appId: '1:579618911646:web:541c90a38841ad34d6928f',
    messagingSenderId: '579618911646',
    projectId: 'newchatapp-8267c',
    authDomain: 'newchatapp-8267c.firebaseapp.com',
    storageBucket: 'newchatapp-8267c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSxWgXJNEaw8HRDRWBnfCo2osWX0KDpFw',
    appId: '1:579618911646:android:2bdd245c2af9faf6d6928f',
    messagingSenderId: '579618911646',
    projectId: 'newchatapp-8267c',
    storageBucket: 'newchatapp-8267c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqh2A8tD29V-5ysOABL4pbQzm-zUHmX4',
    appId: '1:579618911646:ios:d835f8fef22b5832d6928f',
    messagingSenderId: '579618911646',
    projectId: 'newchatapp-8267c',
    storageBucket: 'newchatapp-8267c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqh2A8tD29V-5ysOABL4pbQzm-zUHmX4',
    appId: '1:579618911646:ios:d835f8fef22b5832d6928f',
    messagingSenderId: '579618911646',
    projectId: 'newchatapp-8267c',
    storageBucket: 'newchatapp-8267c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4_yaggdYnJV_nqEzy4cIIBmejI1SbUIM',
    appId: '1:579618911646:web:5fbe4b85a1bbf957d6928f',
    messagingSenderId: '579618911646',
    projectId: 'newchatapp-8267c',
    authDomain: 'newchatapp-8267c.firebaseapp.com',
    storageBucket: 'newchatapp-8267c.appspot.com',
  );
}
